baseURL = 'https://jarno.ruokamo.eu'
languageCode = 'fi-fi'
disableKinds = [ "RSS", "taxonomy", "section", "404" ]
enableGitInfo = true

[params]
	nimi = "Jarno Ruokamo"
	osoite = "jarno.ruokamo.eu"
	otsikko = "Curriculum Vitae"
	otsikko_en = "Curriculum Vitae"
	esitys = "Pesunkestävä rovaniemeläinen, lapsuudesta tietokoneiden kanssa harrastellut insinööri. Kouluissa tutustunut myös elektroniikkaan, tietoliikennetekniikkaan ja ohjelmointiin. Nykyisin pelailun lisäksi hiukan C# ja PHP ohjelmointia harrastuksena."
	esitys_en = "Born and raised in Rovaniemi, an engineer for whom computers have been my hobby since childhood. Trained in electronics, information technology and programming in school. Todays hobbies are gaming, C# and PHP programming."
	
	[params.some]
		otsikko = "Linkit"
		otsikko_en = "Links"

		[[params.some.lista]]
			ikoni = "svg/email.svg"
			url = "mailto:jarno@ruokamo.eu"
			name = "Sähköposti"

		[[params.some.lista]]
			ikoni = "svg/facebook.svg"
			url = "https://www.facebook.com/jarno.ruokamo/"
			name = "Facebook"

		[[params.some.lista]]
			ikoni = "svg/instagram.svg"
			url = "https://www.instagram.com/zagna85/"
			name = "Instagram"

		[[params.some.lista]]
			ikoni = "svg/x.svg"
			url = "https://x.com/zagna85"
			name = "X"

		[[params.some.lista]]
			ikoni = "svg/github.svg"
			url = "https://github.com/Zagna"
			name = "Github"

		[[params.some.lista]]
			ikoni = "svg/linkedin.svg"
			url = "https://www.linkedin.com/in/jarno-ruokamo/"
			name = "Linkedin"

	[params.kieli]
		otsikko = "Kielitaito"
		otsikko_en = "Languages"

		[[params.kieli.lista]]
			kieli = "Suomi"
			taso = "Äidinkieli"
			kieli_en = "Finnish"
			taso_en = "Native"
				
		[[params.kieli.lista]]
			kieli = "Englanti"
			taso = "Erinomainen"
			kieli_en = "English"
			taso_en = "Excellent"

	[params.tyokokemus]
		otsikko = "Työkokemus"
		otsikko_en = "Work experience"
		ikoni = "svg/work.svg"

		[[params.tyokokemus.lista]]
			paikka = "Web Developer"
			aika = "2021 &rarr;"
			url = "https://www.hoyry.net"
			yritys = "Digi- ja mainostoimisto Höyry"
			logo = "svg/hoyry.svg"

		[[params.tyokokemus.lista]]
			paikka = "Junior Web Developer"
			aika = "2020 - 2021"
			url = "https://www.hoyry.net"
			yritys = "Digi- ja mainostoimisto Höyry"
			logo = "svg/hoyry.svg"

		[[params.tyokokemus.lista]]
			paikka = "Junior Web Developer"
			aika = "2019"
			url = "https://eduro.fi"
			yritys = "Eduro-säätiö"
			logo = "svg/eduro.svg"

		[[params.tyokokemus.lista]]
			paikka = "Harjoittelija"
			aika = "2018 - 2019"
			url = "https://www.hoyry.net"
			yritys = "Digi- ja mainostoimisto Höyry"
			logo = "svg/hoyry.svg"

		[[params.tyokokemus.lista]]
			paikka = "Suunnittelija"
			aika = "2013 - 2014"
			url = "https://www.metsa.fi"
			yritys = "Metsähallitus"
			logo = "svg/metsa.svg"

		[[params.tyokokemus.lista]]
			paikka = "Laboratorioinsinööri, siviilipalvelus"
			aika = "2011 - 2012"
			url = "https://www.lapinamk.fi"
			yritys = "Lapland University of Applied Sciences"
			logo = "svg/ramk.svg"

	[params.koulutus]
		otsikko = "Koulutus"
		otsikko_en = "Education"
		ikoni = "svg/graduation.svg"

		[[params.koulutus.lista]]
			tutkinto = "Liiketoiminnan ammattitutkinto"
			tarkennus = "Myynnin ja markkinointiviestinnän osaamisala"
			koulu = "Rastor-instituutti"
			url = "https://www.rastorinst.fi"
			aika = "2020 - 2021"
			logo = "svg/rastor.svg"

		[[params.koulutus.lista]]
			tutkinto = "Bachelor of Engineering"
			tarkennus = "Degree Programme in Information Technology"
			koulu = "Lapland University of Applied Sciences"
			url = "https://www.lapinamk.fi"
			aika = "2007 - 2012"
			lopputyo = "Arduino Shield Designs for Electronics Laboratory Studies"
			lopputyon_url = "https://www.theseus.fi/handle/10024/52409"
			logo = "svg/ramk.svg"

		[[params.koulutus.lista]]
			tutkinto = "Sähköalan perustutkinto"
			tarkennus = "Elektroniikan ja tietoliikennetekniikan opetusohjelma"
			koulu = "Lapin ammattioppilaitos"
			url = "https://redu.fi"
			aika = "2001 - 2006"
			logo = "svg/redu.svg"

		[[params.koulutus.lista]]
			tutkinto = "Ylioppilastutkinto"
			koulu = "Rovaniemen aikuislukio"
			url = "http://www.rovaniemenaikuislukio.fi"
			aika = "2001 - 2006"
			logo = "svg/lukio.svg"

	[params.projektit]
		otsikko = "Projektit"
		otsikko_en = "Projects"
		ikoni = "svg/hobby.svg"

		[[params.projektit.lista]]
			asia = "paint.net suomeksi"
			asia_en = "paint.net in finnish"
			url = "https://paint.ruokamo.eu"
			selitys = "paint.net kuvankäsittelyohjelman suomenkielinen käännös ja ohje."
			selitys_en = "Finnish translation and guide for the paint.net image editor"

		[[params.projektit.lista]]
			asia = "OpenRaster Filetype"
			asia_en = "OpenRaster Filetype"
			url = "https://github.com/Zagna/openraster_pdn"
			selitys = "paint.net kuvankäsittelyohjelman lisäosa tiedostotyypin OpenRaster (.ora) avaamiseen ja tallentamiseen."
			selitys_en = "Plugin for opening and saving OpenRaster (.ora) files for the paint.net image editor"

			